from ariadion_language import (
    Angle,
    AngleUnit,
    Bit,
    Program,
    ProgramId,
    SourceNodeId,
    SourceRange,
    Qubit,
    deg,
    rad,
    turns,
)
from ariadion_semantics import Basis, BasisNamespace, basis
from ariadion_runtime import (
    ExecutionTrace,
    ExactClassicalDistribution,
    INSPECTION_SCHEMA_VERSION,
    LogicalRunResult,
    MeasurementBitOrder,
    ObservationExecutionKind,
    RunResult,
    RotationAxis,
    RotationEffect,
    RotationExplanation,
    RotationSourceAngle,
    StateSnapshot,
    TraceDebuggerError,
    TraceDebuggerSession,
    TRACE_DEBUGGER_SCHEMA_VERSION,
    TraceInspection,
    TraceCaptureOptions,
    TraceStepViewModel,
    inspect_execution_trace,
    run_logical_program,
    run_program,
)

__version__ = "0.1.0"


def run(
    program: Program,
    *,
    trace: TraceCaptureOptions | None = None,
) -> RunResult:
    return run_program(program, trace=trace)


__all__ = [
    "Angle",
    "AngleUnit",
    "Basis",
    "BasisNamespace",
    "Bit",
    "ExecutionTrace",
    "ExactClassicalDistribution",
    "INSPECTION_SCHEMA_VERSION",
    "MeasurementBitOrder",
    "LogicalRunResult",
    "ObservationExecutionKind",
    "Program",
    "ProgramId",
    "Qubit",
    "RunResult",
    "RotationAxis",
    "RotationEffect",
    "RotationExplanation",
    "RotationSourceAngle",
    "SourceNodeId",
    "SourceRange",
    "StateSnapshot",
    "TraceDebuggerError",
    "TraceDebuggerSession",
    "TRACE_DEBUGGER_SCHEMA_VERSION",
    "TraceInspection",
    "TraceCaptureOptions",
    "TraceStepViewModel",
    "basis",
    "inspect_execution_trace",
    "deg",
    "rad",
    "run",
    "run_logical_program",
    "turns",
]
